version: 2.1
jobs:
  test_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make MODE=debug tests -j
      - run:
          name: Run
          command: ./bin/run_tests
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make MODE=dev -j
workflows:
  version: 2.1
  build_and_run:
    jobs:
      - test_gcc_latest
      - build_gcc_latest
