version: 2.1
jobs:
  test_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make -C ./src test_program -j
      - run:
          name: Run
          command: ./bin/test_program
  build_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make -C ./src -j
workflows:
  version: 2.1
  build_and_run:
    jobs:
      - test_gcc_latest
      - build_gcc_latest
