version: 2.1
jobs:
  build_and_run_gcc_latest:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build
          command: make -C ./src -j
      - run:
          name: Run
          command: ./bin/iseeaparse
workflows:
  version: 2.1
  build_and_run:
    jobs:
      - build_and_run_gcc_latest
