name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make tests
      run: make tests
    - name: Correr tests
      run: timeout 300s ./bin/run_tests
    - name: Install ValGrind
      run: sudo apt install -y valgrind
    - name: ValGrind
      run: valgrind --error-exitcode=1 --log-file=./log --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./bin/run_tests > /dev/null
    - name: ValGrind fallo
      if: failure()
      run: cat log
